Trigger custom variable expire event on restart
crowbartools/Firebot pull request #1468
Opened 2021-11-24 15:57 UTC by Roger

### Description of the Change

Trigger the event, when Firebot persist custom variables is enabled, even if Firebot was not running when the expiration happened (if not running, it will trigger the event on the next start).

### Applicable Issues

### Testing

Tested the expiration of the custom variable both with Firebot running and with Firebot closed when the expiration should happen

### Screenshots

2021-11-24 17:48 UTC, SReject requested changes

2021-11-24 17:48 UTC, SReject commented on backend/common/custom-variable-manager.js
> +function onCustomVariableExpire(key, value) {
use fat arrow functions for methods that are not associated with a `this`:

```js
const onCustomVariableExpire = (key, value) => {
```

2021-11-24 17:50 UTC, SReject commented
Pull requests should fork from v5 and then merge against v5 :

2021-11-24 17:50 UTC, ebiggz commented
Thanks for the contribution!

2021-11-24 18:09 UTC, Roger commented
Hi! is there any guidelines for contributions? should I then rebase the PR using v5 branch instead of master?

2021-11-25 00:17 UTC, ebiggz commented
@Roger We don't have contributor guidelines at this time, unfortunately. Sorry about that! We discussed getting some defined here soon. 

But yes, rebasing to v5 would be great. We currently have it such that `master` represents the latest stable release and `v5` is our active development branch. When we are ready for a release, we merge to `master` and our CICD makes a build for us.

2021-11-25 01:00 UTC, Roger commented
Sorry I pushed an stale v5 branch from my fork, I just re-pushed updating from upstream and thanks for changing the base branch to v5!

2021-11-25 01:25 UTC, ebiggz approved these changes

2021-11-25 01:28 UTC, ebiggz commented
Looks great. I'll get this merged so it can be in the next stable release. Thanks again for contributing!

2021-11-25 01:28 UTC, merged