Add $customVarialbeKeys[] variable to extract object keys
crowbartools/Firebot pull request #1637
Opened 2022-03-24 01:13 UTC by Samuel38

### Description of the Change
This adds a $customVarialbeKeys[variableName] variable that extracts the array of keys of a custom variable. 

### Applicable Issues
https://github.com/crowbartools/Firebot/issues/1618

### Testing
Created a custom command to create custom variables and output the result of the custom variables keys. 
Also successfully tried to loop over the resulting array of keys. 

### Screenshots
![image](https://user-images.githubusercontent.com/6044734/159822282-42faaf4a-b4e1-4822-87db-8d5e7edf13ca.png)

2022-03-24 04:11 UTC, ebiggz requested changes
Great work! Thanks for taking the time to implementing this. One super small piece of feedback otherwise looks good to go 🎉

2022-03-24 04:11 UTC, ebiggz commented on backend/variables/builtin/custom-variable-keys.js
> +		let data = customVariableManager.getCustomVariable(name, propertyPath);
Super small thing but we can use `const` instead of `let` since it doesn't get reassigned and we don't expect it to.

2022-03-24 19:01 UTC, Samuel38 commented
That's a good point. I made the change.

2022-03-27 12:10 UTC, SReject requested changes
We use 4 spaces for indents. and line-feed(`\x0A`) for end-of-line

2022-03-27 12:24 UTC, SReject commented
A big issue that we should have spotted sooner:

Master branch is used for current latest release. All dev work happens against the v5 branch. You will need to fork from the v5 branch and move your work over to it.

2022-03-27 12:24 UTC, closed without merging