feat:chatUserColor Var
crowbartools/Firebot pull request #2439
Opened 2024-03-03 09:24 UTC by CKY-

Description of the Change
added user chat color variable
added associated Chat Api Endpoint

Applicable Issues
https://github.com/crowbartools/Firebot/issues/2415

Testing
used in a chat message command, preset effect and event to verify that the user hex color was returned
returns White instead of string empty to not break CSS or other styling for other use cases.

2024-03-03 18:03 UTC, heyaapl reviewed
Validated that this functions - it successfully retrieved the user color when I tested this.

2024-03-03 18:57 UTC, ebiggz commented on src/backend/variables/builtin/twitch/chat/message/chat-user-color.ts
> +            if (username !== null) {
Is there a specific need to only check `null` but not `undefined` here (`!== null`)? If not, using `!= null` like we do below should be used

2024-03-03 19:06 UTC, ebiggz requested changes
Nice work! Just some suggestions to simplify & reduce nesting in the variable logic.

2024-03-03 19:06 UTC, ebiggz commented on src/backend/variables/builtin/twitch/chat/message/chat-user-color.ts
> +
Let's define a "Default color" variable here so we can reuse it below:
```js
const DEFAULT_COLOR = "#ffffff";
```

2024-03-03 19:06 UTC, ebiggz commented on src/backend/variables/builtin/twitch/chat/message/chat-user-color.ts
> +                    return chatColor;
Could simplify these lines to:
```js
return chatColor ?? DEFAULT_COLOR;
```

2024-03-03 19:06 UTC, ebiggz commented on src/backend/variables/builtin/twitch/chat/message/chat-user-color.ts
> +                return chatColor;
```js
return chatColor ?? DEFAULT_COLOR;
```

2024-03-03 19:06 UTC, ebiggz commented on src/backend/variables/builtin/twitch/chat/message/chat-user-color.ts
> +            return "#ffffff";
```js
return DEFAULT_COLOR;
```

2024-03-04 13:42 UTC, CKY- commented
@ebiggz thank you for your feedback, I have updated the changes that you requested. I have a feeling that i need to resubmit this  again.. there is something funky going on with my git and the github website where it is trying to pull from master and not V5. when I click the button here to update button.

2024-03-04 16:16 UTC, ebiggz approved these changes
Looks great!

2024-03-04 16:17 UTC, merged