feat: twitch clip date and feature
crowbartools/Firebot pull request #2695
Opened 2024-08-14 20:38 UTC by CKY-

### Description of the Change

this adds 2 check boxes to the play random clip from twitch 
one for featured only 

one for max age with max age the time input was added so that users can select the amount of time to the current time to get clips from the api request.

and fixed linting
### Applicable Issues

#2594
#1554

### Testing

while coding and playing with this i was randomly targeting chat users 

### Screenshots

![image](https://github.com/user-attachments/assets/29733646-cba6-4cd0-8e93-a94d88ff17aa)

2024-08-15 14:14 UTC, ebiggz requested changes

2024-08-15 14:14 UTC, ebiggz commented on src/backend/effects/builtin/play-video.js
> +                    </div>
Please use the `<firebot-checkbox />` component for this bad boy. I know theres probably other checkboxes in this effect not using the "old way", I'm just trying to make sure at least that any new checkboxes we add are using the component :)

2024-08-15 14:14 UTC, ebiggz commented on src/backend/effects/builtin/play-video.js
> +            </div>
Can use `<firebot-checkbox />` here as well

2024-08-15 14:22 UTC, SReject approved these changes

2024-08-15 15:10 UTC, ebiggz approved these changes

2024-08-15 15:10 UTC, merged

2024-09-22 11:50 UTC, angsaysroar commented
@CKY- this is look really spiffy!

2024-09-23 03:25 UTC, angsaysroar commented
I noticed it doesn’t account for when someone does not have featured clips, so maybe add else if clause if the effect has thee maximum age of a clip play that else play a random clip. 

I hope that made sense. Lol